export enum ErrorCode {
VALIDATION_ERROR = 'VALIDATION_ERROR',
UNKNOW_ERROR = 'UNKNOW_ERROR',
COURIER_CLIENT_ERROR = 'COURIER_CLIENT_ERROR',
COURIER_UNAVAILABLE = 'COURIER_UNAVAILABLE',
COURIER_AUTH_FAILED = 'COURIER_AUTH_FAILED',
ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
BATCH_NOT_FOUND = 'BATCH_NOT_FOUND',
INTERNAL_ERROR = 'INTERNAL_ERROR',
DUPLICATE_ORDER = 'DUPLICATE_ORDER',
}