export enum ShipmentStatus {
    PENDING = 'PENDING',
    CREATED = 'CREATED',
    PICKED_UP = 'PICKED_UP',
    IN_TRANSIT = 'IN_TRANSIT',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    RETURNED = 'RETURNED',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
}